### ISSUE TITLE
key error ['data-date']

### ISSUE THREAD

**Issue by JakubWabinski** [rougier/calendar-heatmap#2]
Hey,

I know that it's been a while since the repo was updated for the last time but I am working on something similar now and wanted to base on your code.

When copying the GITHub activity code I get the error:

```
`Traceback (most recent call last):
  File "C:/Users/jakub.wabinski/OneDrive - Wojskowa Akademia Techniczna/Pulpit/Doktorat/Zatrudnienie/EPOS 2/Wizualizacja_kalendarz/Pycharm_GITHub.py", line 104, in <module>
    calmap(ax, year + i, github_contrib("rougier", year + i), origin="upper")
  File "C:/Users/jakub.wabinski/OneDrive - Wojskowa Akademia Techniczna/Pulpit/Doktorat/Zatrudnienie/EPOS 2/Wizualizacja_kalendarz/Pycharm_GITHub.py", line 43, in github_contrib
    parser.feed(contents)
  File "C:\Users\jakub.wabinski\anaconda3\lib\html\parser.py", line 111, in feed
    self.goahead(0)
  File "C:\Users\jakub.wabinski\anaconda3\lib\html\parser.py", line 171, in goahead
    k = self.parse_starttag(i)
  File "C:\Users\jakub.wabinski\anaconda3\lib\html\parser.py", line 345, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "C:/Users/jakub.wabinski/OneDrive - Wojskowa Akademia Techniczna/Pulpit/Doktorat/Zatrudnienie/EPOS 2/Wizualizacja_kalendarz/Pycharm_GITHub.py", line 36, in handle_starttag
    date = dateutil.parser.parse(data["data-date"])
KeyError: 'data-date'`
```

When looking up the HTML file, this key actually exists in the data. Is the issue within a parser? I am not a programming expert so this might sound trivial to you...

Thanks in advance,

Jakub

**Comment by rougier** [comment]
For the GitHub activity, I'm parsing the HTML file and if GitHub changed their format, this might be the problem. If the key is still here then the problem might be with the parser. Best would be to play with `github_contrib(user, year):` or to find a new way to get the same info.
